In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
comp = pd.read_csv('../../Capstone/Food_Production.csv')

In [3]:
comp.head()

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions (Kg CO2 - equivalents per kg product),Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal),...,Freshwater withdrawals per 100g protein (liters per 100g protein),Freshwater withdrawals per kilogram (liters per kilogram),Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal),Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein),Land use per 1000kcal (square miles per 1000kcal),Land use per kilogram (m² per kilogram),Land use per 100g protein (m² per 100g protein),Scarcity-weighted water use per kilogram (liters per kilogram),Scarcity-weighted water use per 100g protein (liters per 100g protein),Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6,4.281357,...,371.076923,482.4,0.945482,1.907692,2.897446,7.6,5.846154,18786.2,14450.92308,7162.104461
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0,9.514379,...,3166.760563,2248.4,1.207271,6.267606,0.759631,2.8,3.943662,49576.3,69825.77465,13449.891480

In [4]:
## filtering to only the columns I want represented
## shortening column names for easier use / understanding

pared = comp [['Food product','Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
               'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
                'Land use per 1000kcal (square miles per 1000kcal)',
               'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)']]

pared_short = pared.rename(columns={'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)': 'GHG_Emissions',
               'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)': 'Eutrophying_Emissions',
                'Land use per 1000kcal (square miles per 1000kcal)':'Land_Use',
               'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)':'Scarcity_weighted_Water_Use'})

pared_short

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use
0,Wheat & Rye (Bread),NaN,NaN,NaN,NaN
1,Maize (Meal),NaN,NaN,NaN,NaN
2,Barley (Beer),NaN,NaN,NaN,NaN
3,Oatmeal,0.945482,4.281357,2.897446,7162.104461
4,Rice,1.207271,9.514379,0.759631,13449.891480
5,Potatoes,0.628415,4.754098,1.202186,3762.568306
6,Cassava,1.355236,0.708419,1.858316,NaN
7,Cane Sugar,0.911681,4.820513,0.581197,4683.361823
8,Beet Sugar,0.515670,1.541311,0.521368,2704.643875
9,Other Pulses,0.524927,5.008798,4.565982,NaN
10,Peas,0.283237,2.173410,2.156069,NaN
11,Nuts,0.069919,3.113821,2.107317,37380.455280
12,Groundnuts,0.556897,2.437931,1.570690,10654.810340
13,Soymilk,NaN,NaN,NaN,NaN
14,Tofu,NaN,NaN,NaN,NaN
15,Soybean Oil,NaN,NaN,NaN,NaN
16,Palm Oil,0.828054,1.207014,0.273756,4.095023
17,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520
18,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353
19,Olive Oil,0.613122,4.214932,2.976244,20076.945700
20,Tomatoes,11.000000,39.526316,4.210526,28082.631580
21,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919
22,Root Vegetables,1.162162,4.351351,0.891892,2511.351351
23,Brassicas,3.000000,29.470588,3.235294,49735.882350
24,Other Vegetables,NaN,NaN,NaN,NaN
25,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500
26,Bananas,1.433333,5.483333,3.216667,1103.166667
27,Apples,0.895833,3.020833,1.312500,26976.250000
28,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230
29,Wine,NaN,NaN,NaN,NaN
30,Other Fruit,NaN,NaN,NaN,NaN
31,Coffee,50.946429,197.357143,38.607143,601.785714
32,Dark Chocolate,9.023211,16.843327,13.338491,556.905222
33,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470
34,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640
35,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380
36,Pig Meat,5.150628,31.958159,7.263598,27977.991630
37,Poultry Meat,5.335135,26.324324,6.605405,7663.729730
38,Milk,5.250000,17.750000,14.916667,32977.166670
39,Cheese,6.170543,25.418605,22.684755,46731.421190
40,Eggs,3.243056,15.111111,4.354167,12487.986110
41,Fish (farmed),7.614525,131.351955,4.698324,23224.692740
42,Shrimps (farmed),NaN,NaN,NaN,NaN

In [5]:
seafood = pd.read_csv('../../Capstone/ghg-emissions-seafood.csv')

In [6]:
seafood.head(50
            )

,Entity,Code,Year,Greenhouse gas emissions (kg / kg edible weight)
0,Bivalves (farmed),NaN,2021,1.399126
1,Bivalves (wild),NaN,2021,11.400049
2,Carp (farmed),NaN,2021,6.946923
3,Catfish (farmed),NaN,2021,7.774491
4,Chicken,NaN,2021,8.335000
5,"Cod, haddock (wild)",NaN,2021,5.125039
6,Flounder (wild),NaN,2021,20.313314
7,"Herring, sardines (wild)",NaN,2021,3.877940
8,Jack fish (wild),NaN,2021,9.665174
9,Lobster (wild),NaN,2021,19.444952
10,Milkfish (farmed),NaN,2021,6.434887
11,Other freshwater fish (farmed),NaN,2021,18.905922
12,Other marine fish (farmed),NaN,2021,11.595179
13,"Redfish, bass (wild)",NaN,2021,9.914650
14,Salmon (farmed),NaN,2021,5.100986
15,"Salmon, trout (wild)",NaN,2021,6.881339
16,Seaweed (farmed),NaN,2021,1.086723
17,Shrimp (farmed),NaN,2021,9.428016
18,Shrimp (wild),NaN,2021,11.956739
19,Silver/bighead (farmed),NaN,2021,3.510591
20,Squid (wild),NaN,2021,8.184950
21,Tilapia (farmed),NaN,2021,10.675982
22,Trout (farmed),NaN,2021,5.409547
23,Tuna (wild),NaN,2021,7.629054

In [7]:
## dropping nas

pared_nona = pared_short.dropna(subset = ['Scarcity_weighted_Water_Use'])
pared_nona

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use
3,Oatmeal,0.945482,4.281357,2.897446,7162.104461
4,Rice,1.207271,9.514379,0.759631,13449.891480
5,Potatoes,0.628415,4.754098,1.202186,3762.568306
7,Cane Sugar,0.911681,4.820513,0.581197,4683.361823
8,Beet Sugar,0.515670,1.541311,0.521368,2704.643875
11,Nuts,0.069919,3.113821,2.107317,37380.455280
12,Groundnuts,0.556897,2.437931,1.570690,10654.810340
16,Palm Oil,0.828054,1.207014,0.273756,4.095023
17,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520
18,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353
19,Olive Oil,0.613122,4.214932,2.976244,20076.945700
20,Tomatoes,11.000000,39.526316,4.210526,28082.631580
21,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919
22,Root Vegetables,1.162162,4.351351,0.891892,2511.351351
23,Brassicas,3.000000,29.470588,3.235294,49735.882350
25,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500
26,Bananas,1.433333,5.483333,3.216667,1103.166667
27,Apples,0.895833,3.020833,1.312500,26976.250000
28,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230
31,Coffee,50.946429,197.357143,38.607143,601.785714
32,Dark Chocolate,9.023211,16.843327,13.338491,556.905222
33,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470
34,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640
35,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380
36,Pig Meat,5.150628,31.958159,7.263598,27977.991630
37,Poultry Meat,5.335135,26.324324,6.605405,7663.729730
38,Milk,5.250000,17.750000,14.916667,32977.166670
39,Cheese,6.170543,25.418605,22.684755,46731.421190
40,Eggs,3.243056,15.111111,4.354167,12487.986110
41,Fish (farmed),7.614525,131.351955,4.698324,23224.692740

In [8]:
## resetting index now that n/a rows eliminated
new_df = pared_nona.reset_index(drop=True)
new_df

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use
0,Oatmeal,0.945482,4.281357,2.897446,7162.104461
1,Rice,1.207271,9.514379,0.759631,13449.891480
2,Potatoes,0.628415,4.754098,1.202186,3762.568306
3,Cane Sugar,0.911681,4.820513,0.581197,4683.361823
4,Beet Sugar,0.515670,1.541311,0.521368,2704.643875
5,Nuts,0.069919,3.113821,2.107317,37380.455280
6,Groundnuts,0.556897,2.437931,1.570690,10654.810340
7,Palm Oil,0.828054,1.207014,0.273756,4.095023
8,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520
9,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353
10,Olive Oil,0.613122,4.214932,2.976244,20076.945700
11,Tomatoes,11.000000,39.526316,4.210526,28082.631580
12,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919
13,Root Vegetables,1.162162,4.351351,0.891892,2511.351351
14,Brassicas,3.000000,29.470588,3.235294,49735.882350
15,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500
16,Bananas,1.433333,5.483333,3.216667,1103.166667
17,Apples,0.895833,3.020833,1.312500,26976.250000
18,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230
19,Coffee,50.946429,197.357143,38.607143,601.785714
20,Dark Chocolate,9.023211,16.843327,13.338491,556.905222
21,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470
22,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640
23,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380
24,Pig Meat,5.150628,31.958159,7.263598,27977.991630
25,Poultry Meat,5.335135,26.324324,6.605405,7663.729730
26,Milk,5.250000,17.750000,14.916667,32977.166670
27,Cheese,6.170543,25.418605,22.684755,46731.421190
28,Eggs,3.243056,15.111111,4.354167,12487.986110
29,Fish (farmed),7.614525,131.351955,4.698324,23224.692740

In [9]:
## want to add columns for quartiles
new_df.describe()

,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use
count,30.000000,30.000000,30.000000,30.000000
mean,6.125224,29.636681,13.379470,17380.575408
std,11.024197,48.077729,29.601112,16232.080209
min,0.069919,1.207014,0.273756,4.095023
25%,0.844999,4.298856,1.229992,2969.124983
50%,1.392342,9.135568,3.096456,12605.256790
75%,5.961691,28.684022,7.099050,28056.471593
max,50.946429,197.357143,119.490842,49735.882350

In [10]:
##adding GHG percentiles
new_df['GHG_Percentiles'] = new_df.GHG_Emissions.rank(pct = True)
new_df

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use,GHG_Percentiles
0,Oatmeal,0.945482,4.281357,2.897446,7162.104461,0.366667
1,Rice,1.207271,9.514379,0.759631,13449.891480,0.433333
2,Potatoes,0.628415,4.754098,1.202186,3762.568306,0.233333
3,Cane Sugar,0.911681,4.820513,0.581197,4683.361823,0.333333
4,Beet Sugar,0.515670,1.541311,0.521368,2704.643875,0.133333
5,Nuts,0.069919,3.113821,2.107317,37380.455280,0.033333
6,Groundnuts,0.556897,2.437931,1.570690,10654.810340,0.166667
7,Palm Oil,0.828054,1.207014,0.273756,4.095023,0.266667
8,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520,0.066667
9,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353,0.100000
10,Olive Oil,0.613122,4.214932,2.976244,20076.945700,0.200000
11,Tomatoes,11.000000,39.526316,4.210526,28082.631580,0.866667
12,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919,0.500000
13,Root Vegetables,1.162162,4.351351,0.891892,2511.351351,0.400000
14,Brassicas,3.000000,29.470588,3.235294,49735.882350,0.600000
15,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500,0.466667
16,Bananas,1.433333,5.483333,3.216667,1103.166667,0.533333
17,Apples,0.895833,3.020833,1.312500,26976.250000,0.300000
18,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230,0.566667
19,Coffee,50.946429,197.357143,38.607143,601.785714,1.000000
20,Dark Chocolate,9.023211,16.843327,13.338491,556.905222,0.833333
21,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470,0.966667
22,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640,0.900000
23,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380,0.933333
24,Pig Meat,5.150628,31.958159,7.263598,27977.991630,0.666667
25,Poultry Meat,5.335135,26.324324,6.605405,7663.729730,0.733333
26,Milk,5.250000,17.750000,14.916667,32977.166670,0.700000
27,Cheese,6.170543,25.418605,22.684755,46731.421190,0.766667
28,Eggs,3.243056,15.111111,4.354167,12487.986110,0.633333
29,Fish (farmed),7.614525,131.351955,4.698324,23224.692740,0.800000

In [11]:
##adding the rest of the percentiles
new_df['Eutrophying_Percentiles'] = new_df.Eutrophying_Emissions.rank(pct = True)
new_df['Land_Percentiles'] = new_df.Land_Use.rank(pct = True)
new_df['Weighted_Water_Percentiles'] = new_df.Scarcity_weighted_Water_Use.rank(pct = True)
new_df

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use,GHG_Percentiles,Eutrophying_Percentiles,Land_Percentiles,Weighted_Water_Percentiles
0,Oatmeal,0.945482,4.281357,2.897446,7162.104461,0.366667,0.266667,0.466667,0.400000
1,Rice,1.207271,9.514379,0.759631,13449.891480,0.433333,0.533333,0.133333,0.566667
2,Potatoes,0.628415,4.754098,1.202186,3762.568306,0.233333,0.333333,0.233333,0.300000
3,Cane Sugar,0.911681,4.820513,0.581197,4683.361823,0.333333,0.366667,0.100000,0.366667
4,Beet Sugar,0.515670,1.541311,0.521368,2704.643875,0.133333,0.066667,0.066667,0.266667
5,Nuts,0.069919,3.113821,2.107317,37380.455280,0.033333,0.200000,0.400000,0.866667
6,Groundnuts,0.556897,2.437931,1.570690,10654.810340,0.166667,0.133333,0.333333,0.466667
7,Palm Oil,0.828054,1.207014,0.273756,4.095023,0.266667,0.033333,0.033333,0.033333
8,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520,0.066667,0.433333,0.366667,0.333333
9,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353,0.100000,0.100000,0.266667,0.166667
10,Olive Oil,0.613122,4.214932,2.976244,20076.945700,0.200000,0.233333,0.500000,0.633333
11,Tomatoes,11.000000,39.526316,4.210526,28082.631580,0.866667,0.866667,0.600000,0.766667
12,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919,0.500000,0.500000,0.200000,0.233333
13,Root Vegetables,1.162162,4.351351,0.891892,2511.351351,0.400000,0.300000,0.166667,0.200000
14,Brassicas,3.000000,29.470588,3.235294,49735.882350,0.600000,0.766667,0.566667,1.000000
15,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500,0.466667,0.466667,0.433333,0.600000
16,Bananas,1.433333,5.483333,3.216667,1103.166667,0.533333,0.400000,0.533333,0.133333
17,Apples,0.895833,3.020833,1.312500,26976.250000,0.300000,0.166667,0.300000,0.700000
18,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230,0.566667,0.566667,0.633333,0.833333
19,Coffee,50.946429,197.357143,38.607143,601.785714,1.000000,1.000000,0.933333,0.100000
20,Dark Chocolate,9.023211,16.843327,13.338491,556.905222,0.833333,0.633333,0.800000,0.066667
21,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470,0.966667,0.900000,1.000000,0.533333
22,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640,0.900000,0.966667,0.866667,0.900000
23,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380,0.933333,0.800000,0.966667,0.933333
24,Pig Meat,5.150628,31.958159,7.263598,27977.991630,0.666667,0.833333,0.766667,0.733333
25,Poultry Meat,5.335135,26.324324,6.605405,7663.729730,0.733333,0.733333,0.733333,0.433333
26,Milk,5.250000,17.750000,14.916667,32977.166670,0.700000,0.666667,0.833333,0.800000
27,Cheese,6.170543,25.418605,22.684755,46731.421190,0.766667,0.700000,0.900000,0.966667
28,Eggs,3.243056,15.111111,4.354167,12487.986110,0.633333,0.600000,0.666667,0.500000
29,Fish (farmed),7.614525,131.351955,4.698324,23224.692740,0.800000,0.933333,0.700000,0.666667

In [12]:
new_df['enviro_sum_percentiles'] = (new_df['Eutrophying_Percentiles'] + new_df['Land_Percentiles'] + 
                          new_df['Weighted_Water_Percentiles'] + new_df['GHG_Percentiles'])
new_df

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use,GHG_Percentiles,Eutrophying_Percentiles,Land_Percentiles,Weighted_Water_Percentiles,enviro_sum_percentiles
0,Oatmeal,0.945482,4.281357,2.897446,7162.104461,0.366667,0.266667,0.466667,0.400000,1.500000
1,Rice,1.207271,9.514379,0.759631,13449.891480,0.433333,0.533333,0.133333,0.566667,1.666667
2,Potatoes,0.628415,4.754098,1.202186,3762.568306,0.233333,0.333333,0.233333,0.300000,1.100000
3,Cane Sugar,0.911681,4.820513,0.581197,4683.361823,0.333333,0.366667,0.100000,0.366667,1.166667
4,Beet Sugar,0.515670,1.541311,0.521368,2704.643875,0.133333,0.066667,0.066667,0.266667,0.533333
5,Nuts,0.069919,3.113821,2.107317,37380.455280,0.033333,0.200000,0.400000,0.866667,1.500000
6,Groundnuts,0.556897,2.437931,1.570690,10654.810340,0.166667,0.133333,0.333333,0.466667,1.100000
7,Palm Oil,0.828054,1.207014,0.273756,4.095023,0.266667,0.033333,0.033333,0.033333,0.366667
8,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520,0.066667,0.433333,0.366667,0.333333,1.200000
9,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353,0.100000,0.100000,0.266667,0.166667,0.633333
10,Olive Oil,0.613122,4.214932,2.976244,20076.945700,0.200000,0.233333,0.500000,0.633333,1.566667
11,Tomatoes,11.000000,39.526316,4.210526,28082.631580,0.866667,0.866667,0.600000,0.766667,3.100000
12,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919,0.500000,0.500000,0.200000,0.233333,1.433333
13,Root Vegetables,1.162162,4.351351,0.891892,2511.351351,0.400000,0.300000,0.166667,0.200000,1.066667
14,Brassicas,3.000000,29.470588,3.235294,49735.882350,0.600000,0.766667,0.566667,1.000000,2.933333
15,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500,0.466667,0.466667,0.433333,0.600000,1.966667
16,Bananas,1.433333,5.483333,3.216667,1103.166667,0.533333,0.400000,0.533333,0.133333,1.600000
17,Apples,0.895833,3.020833,1.312500,26976.250000,0.300000,0.166667,0.300000,0.700000,1.466667
18,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230,0.566667,0.566667,0.633333,0.833333,2.600000
19,Coffee,50.946429,197.357143,38.607143,601.785714,1.000000,1.000000,0.933333,0.100000,3.033333
20,Dark Chocolate,9.023211,16.843327,13.338491,556.905222,0.833333,0.633333,0.800000,0.066667,2.333333
21,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470,0.966667,0.900000,1.000000,0.533333,3.400000
22,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640,0.900000,0.966667,0.866667,0.900000,3.633333
23,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380,0.933333,0.800000,0.966667,0.933333,3.633333
24,Pig Meat,5.150628,31.958159,7.263598,27977.991630,0.666667,0.833333,0.766667,0.733333,3.000000
25,Poultry Meat,5.335135,26.324324,6.605405,7663.729730,0.733333,0.733333,0.733333,0.433333,2.633333
26,Milk,5.250000,17.750000,14.916667,32977.166670,0.700000,0.666667,0.833333,0.800000,3.000000
27,Cheese,6.170543,25.418605,22.684755,46731.421190,0.766667,0.700000,0.900000,0.966667,3.333333
28,Eggs,3.243056,15.111111,4.354167,12487.986110,0.633333,0.600000,0.666667,0.500000,2.400000
29,Fish (farmed),7.614525,131.351955,4.698324,23224.692740,0.800000,0.933333,0.700000,0.666667,3.100000

In [13]:
new_df['enviro_sum'] = (new_df['GHG_Emissions'] + new_df['Land_Use'] + 
                          new_df['Scarcity_weighted_Water_Use'] + new_df['Eutrophying_Emissions'])
new_df

,Food product,GHG_Emissions,Eutrophying_Emissions,Land_Use,Scarcity_weighted_Water_Use,GHG_Percentiles,Eutrophying_Percentiles,Land_Percentiles,Weighted_Water_Percentiles,enviro_sum_percentiles,enviro_sum
0,Oatmeal,0.945482,4.281357,2.897446,7162.104461,0.366667,0.266667,0.466667,0.400000,1.500000,7170.228746
1,Rice,1.207271,9.514379,0.759631,13449.891480,0.433333,0.533333,0.133333,0.566667,1.666667,13461.372761
2,Potatoes,0.628415,4.754098,1.202186,3762.568306,0.233333,0.333333,0.233333,0.300000,1.100000,3769.153005
3,Cane Sugar,0.911681,4.820513,0.581197,4683.361823,0.333333,0.366667,0.100000,0.366667,1.166667,4689.675213
4,Beet Sugar,0.515670,1.541311,0.521368,2704.643875,0.133333,0.066667,0.066667,0.266667,0.533333,2707.222223
5,Nuts,0.069919,3.113821,2.107317,37380.455280,0.033333,0.200000,0.400000,0.866667,1.500000,37385.746337
6,Groundnuts,0.556897,2.437931,1.570690,10654.810340,0.166667,0.133333,0.333333,0.466667,1.100000,10659.375857
7,Palm Oil,0.828054,1.207014,0.273756,4.095023,0.266667,0.033333,0.033333,0.033333,0.366667,6.403846
8,Sunflower Oil,0.407240,5.730769,1.997738,4114.185520,0.066667,0.433333,0.366667,0.333333,1.200000,4122.321267
9,Rapeseed Oil,0.426471,2.170814,1.202489,1198.382353,0.100000,0.100000,0.266667,0.166667,0.633333,1202.182127
10,Olive Oil,0.613122,4.214932,2.976244,20076.945700,0.200000,0.233333,0.500000,0.633333,1.566667,20084.749999
11,Tomatoes,11.000000,39.526316,4.210526,28082.631580,0.866667,0.866667,0.600000,0.766667,3.100000,28137.368422
12,Onions & Leeks,1.351351,8.756757,1.054054,2518.918919,0.500000,0.500000,0.200000,0.233333,1.433333,2530.081081
13,Root Vegetables,1.162162,4.351351,0.891892,2511.351351,0.400000,0.300000,0.166667,0.200000,1.066667,2517.756756
14,Brassicas,3.000000,29.470588,3.235294,49735.882350,0.600000,0.766667,0.566667,1.000000,2.933333,49771.588232
15,Citrus Fruit,1.218750,7.000000,2.687500,14570.937500,0.466667,0.466667,0.433333,0.600000,1.966667,14581.843750
16,Bananas,1.433333,5.483333,3.216667,1103.166667,0.533333,0.400000,0.533333,0.133333,1.600000,1113.300000
17,Apples,0.895833,3.020833,1.312500,26976.250000,0.300000,0.166667,0.300000,0.700000,1.466667,26981.479167
18,Berries & Grapes,2.684211,10.736842,4.228070,37126.491230,0.566667,0.566667,0.633333,0.833333,2.600000,37144.140353
19,Coffee,50.946429,197.357143,38.607143,601.785714,1.000000,1.000000,0.933333,0.100000,3.033333,888.696429
20,Dark Chocolate,9.023211,16.843327,13.338491,556.905222,0.833333,0.633333,0.800000,0.066667,2.333333,596.110251
21,Beef (beef herd),36.439560,110.406593,119.490842,12722.527470,0.966667,0.900000,1.000000,0.533333,3.400000,12988.864466
22,Beef (dairy herd),12.197802,133.805861,15.838828,43884.688640,0.900000,0.966667,0.866667,0.900000,3.633333,44046.531131
23,Lamb & Mutton,12.529968,30.640379,116.659306,44771.293380,0.933333,0.800000,0.966667,0.933333,3.633333,44931.123033
24,Pig Meat,5.150628,31.958159,7.263598,27977.991630,0.666667,0.833333,0.766667,0.733333,3.000000,28022.364015
25,Poultry Meat,5.335135,26.324324,6.605405,7663.729730,0.733333,0.733333,0.733333,0.433333,2.633333,7701.994595
26,Milk,5.250000,17.750000,14.916667,32977.166670,0.700000,0.666667,0.833333,0.800000,3.000000,33015.083337
27,Cheese,6.170543,25.418605,22.684755,46731.421190,0.766667,0.700000,0.900000,0.966667,3.333333,46785.695092
28,Eggs,3.243056,15.111111,4.354167,12487.986110,0.633333,0.600000,0.666667,0.500000,2.400000,12510.694443
29,Fish (farmed),7.614525,131.351955,4.698324,23224.692740,0.800000,0.933333,0.700000,0.666667,3.100000,23368.357544

In [14]:
df_melt_long=new_df.melt(id_vars='Food product',var_name='Measure Type',value_name='Value')

In [15]:
df_melt_long.head(40)

         Food product           Measure Type      Value
0             Oatmeal          GHG_Emissions   0.945482
1                Rice          GHG_Emissions   1.207271
2            Potatoes          GHG_Emissions   0.628415
3          Cane Sugar          GHG_Emissions   0.911681
4          Beet Sugar          GHG_Emissions   0.515670
5                Nuts          GHG_Emissions   0.069919
6          Groundnuts          GHG_Emissions   0.556897
7            Palm Oil          GHG_Emissions   0.828054
8       Sunflower Oil          GHG_Emissions   0.407240
9        Rapeseed Oil          GHG_Emissions   0.426471
10          Olive Oil          GHG_Emissions   0.613122
11           Tomatoes          GHG_Emissions  11.000000
12     Onions & Leeks          GHG_Emissions   1.351351
13    Root Vegetables          GHG_Emissions   1.162162
14          Brassicas          GHG_Emissions   3.000000
15       Citrus Fruit          GHG_Emissions   1.218750
16            Bananas          GHG_Emissions   1.433333
17             Apples          GHG_Emissions   0.895833
18   Berries & Grapes          GHG_Emissions   2.684211
19             Coffee          GHG_Emissions  50.946429
20     Dark Chocolate          GHG_Emissions   9.023211
21   Beef (beef herd)          GHG_Emissions  36.439560
22  Beef (dairy herd)          GHG_Emissions  12.197802
23      Lamb & Mutton          GHG_Emissions  12.529968
24           Pig Meat          GHG_Emissions   5.150628
25       Poultry Meat          GHG_Emissions   5.335135
26               Milk          GHG_Emissions   5.250000
27             Cheese          GHG_Emissions   6.170543
28               Eggs          GHG_Emissions   3.243056
29      Fish (farmed)          GHG_Emissions   7.614525
30            Oatmeal  Eutrophying_Emissions   4.281357
31               Rice  Eutrophying_Emissions   9.514379
32           Potatoes  Eutrophying_Emissions   4.754098
33         Cane Sugar  Eutrophying_Emissions   4.820513
34         Beet Sugar  Eutrophying_Emissions   1.541311
35               Nuts  Eutrophying_Emissions   3.113821
36         Groundnuts  Eutrophying_Emissions   2.437931
37           Palm Oil  Eutrophying_Emissions   1.207014
38      Sunflower Oil  Eutrophying_Emissions   5.730769
39       Rapeseed Oil  Eutrophying_Emissions   2.170814

In [16]:
new_df.to_csv('../data/FINAL_cap.csv', index = False)

In [17]:
df_melt_long.to_csv('../data/cap_df_melted',index=False)